### ISSUE TITLE
Add Command Shop

### ISSUE THREAD

**Issue by Lentou** [DaPigGuy/PiggyShopUI#10]
Suggestion:
Add Command in Shop like
You can buy commands
-
Example:
Player wants to buy a Player Rank in shop then
command /setgroup Player Donator will execute if the player buys the command

Bug:
The non-op players can use /shop edit

**Comment by provsalt** [comment]
> ## Suggestion:
> Add Command in Shop like
> You can buy commands
> Example:
> Player wants to buy a Player Rank in shop then
> command /setgroup Player Donator will execute if the player buys the command
No

**Comment by Aericio** [comment]
Bug has been fixed in https://github.com/DaPigGuy/PiggyShopUI/commit/114811d7df9a888d475a72772ebede05a35b50dd
