### ISSUE TITLE
Language System

### ISSUE THREAD

**Issue by junxiesky** [DaPigGuy/PiggyShopUI#14]
I need the ability to customize the product name functionality.
Because in my country, many players can't understand English.

**Comment by Aericio** [comment]
Very low chance of this being implemented since PiggyShopUI is not very popular.

**Comment by junxiesky** [comment]
> 由于PiggyShopUI不太流行，因此实现此功能的可能性很小。

oh...
What am I supposed to do?

**Comment by Aericio** [comment]
我可以帮你要是你会翻译 (so I can modify directly)，还是你只可以等。

I can help you if you are able to translate (so I can modify directly), or else you can only wait.

**Comment by Aericio** [comment]
Actually, I was mistaken. I forgot that that you can do so in `config.yml`.

**Comment by junxiesky** [comment]
@Aericio 
no,no,no
I think you've mistaken my meaning
I mean, custom trade names
For example, the name of the diamond is the best stone

**Comment by Aericio** [comment]
Can you show me image of what you mean?

**Comment by junxiesky** [comment]
> Can you show me image of what you mean?

For example:
I want to change the name of the diamond to the best stone.

**Comment by junxiesky** [comment]
I mean, custom item name.

**Comment by junxiesky** [comment]
My English is not very good, I hope you can understand what I mean.

**Comment by junxiesky** [comment]
@Aericio

**Comment by junxiesky** [comment]
![IMG_20200224_180535](https://user-images.githubusercontent.com/30452768/75143656-630c0400-5730-11ea-8772-379db148b56c.jpg)

**Comment by YxMingY** [comment]
Well, His meaning is :
  When chinese people shop for items in server, they cannot understand the items' English name so that they cannot find the item they want.
  He want you to add a feature to make the items' shown name change into chinses(for example "apple" be turned into "苹果" to show to player)

**Comment by Aericio** [comment]
I see. Wait for @DaPigGuy.

**Comment by Thunder33345** [comment]
isnt this more like a PMMP item naming thing? assuming we depend on PMMP for item readable localized name

**Comment by Aericio** [comment]
That's what I was assuming, but I wasn't completely sure.
