### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by jaylac2000** [DaPigGuy/PiggyShopUI#17]
Rather than it say x1 make it show 

Item - Price 

![Uploading C7A58E29-C230-4A18-A49B-5DBAF13CE2EE.png…]()

**Comment by Aericio** [comment]
Image did not upload.

**Comment by jaylac2000** [comment]
Currently this is what it shows in /shop

“x1 itemName”

You should make it show 

“ItemName - Price”

So people can see how much the item costs without clicking on it

**Comment by ZZWILLIAMXXTrue** [comment]
Make it customizable in the config instead and add,
{price}
{itemname}
{count}

**Comment by jaylac2000** [comment]
i didnt see that, thank you

**Comment by jaylac2000** [comment]
![86C80261-99BA-4E32-8E8A-CF92970B27E0](https://user-images.githubusercontent.com/53111006/81313778-4eb08580-9056-11ea-881c-64e2e55426a7.png)

**Comment by jaylac2000** [comment]
Didn’t appear to work for me

**Comment by jaylac2000** [comment]
heres my config so nothing is spelled wrong https://pastebin.com/Qk1tRFqg

**Comment by DaPigGuy** [comment]
{BUYPRICE} & {SELLPRICE}
