### ISSUE TITLE
Add color names

### ISSUE THREAD

**Issue by jaylac2000** [DaPigGuy/PiggyShopUI#19]
Dye doesn’t appear in shop as it’s colour to the point I need to add a description but than there’s no back button so people need to exit the shop than go back 
![80500757-0463-4F89-9889-5C5BCA3C9A03](https://user-images.githubusercontent.com/53111006/81389779-5b7db980-90e8-11ea-8e4f-af5cf0679fe0.png)
![DC2F9434-990E-42CA-A2B8-C9A39069E530](https://user-images.githubusercontent.com/53111006/81389786-5c165000-90e8-11ea-9e7c-d973a64f2f51.png)

**Comment by jaylac2000** [comment]
also does it with a water bucket & a lava bucket

**Comment by jaylac2000** [comment]
terracotta changes the name in shop to clay

**Comment by Aericio** [comment]
Can you upload your `shops.yml` file to https://hastebin.com/?

**Comment by ZZWILLIAMXXTrue** [comment]
Same thing happens with Potions and Splash potions, but every time I try to remove them, it come back!

**Comment by jaylac2000** [comment]
i did everything in game https://hastebin.com/layakaciqu.m

**Comment by Aericio** [comment]
Yeah, I just wanted it so I didn't have to create it myself. Thanks.

**Comment by jaylac2000** [comment]
ahh, no problem

**Comment by jaylac2000** [comment]
i dont wanna open a new ticket for a simple question, but how do i give access to a certain rank to view a "private category" shop

**Comment by jaylac2000** [comment]
what is the perm

**Comment by Aericio** [comment]
It says in the readme:
| Permissions | Description | Default |
| --- | --- | --- |
| `piggyshopui.category.{CATEGORY}` | Allows access to private categories | `op` |
