### ISSUE TITLE
adding dye in shop, i have no idea what i am doing

### ISSUE THREAD

**Issue by jaylac2000** [DaPigGuy/PiggyShopUI#31]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyShopUI
- * [ ] Have a detailed title.

### Issue Description

adding dye to the shop, confusing cuz it just says dye rather than what it was, i know i reported this before for buying the item but thought this was fixed also

- Expected result: What were you expecting to happen?

be able to see what i am adding 

- Actual result: What actually happened?

it adds the item to the shop the way it is supposed to (since my last issue) (#19)

#### Steps to Reproduce the Issue

1. join server
2. run /gamemode c
3. grab dye
4. /shop edit and try to add

### OS and Versions

* PocketMine-MP: latest
* PiggyShopUI: latest poggit release
* PHP: latest
* Server OS: linux

### Extra Information

![image](https://user-images.githubusercontent.com/53111006/92058976-f8322a00-ed5d-11ea-84cf-37c1cb7fb378.png)

**Comment by jaylac2000** [comment]
my bad, i given the title the incorrect item name

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyShopUI/pull/40
