### ISSUE TITLE
multi economy in form

### ISSUE THREAD

**Issue by jaylac2000** [DaPigGuy/PiggyShopUI#32]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description

Add support for multi economy option (when creating category) - so you can choose which currency that category is

### Extra Information

- . . . .

**Comment by Aericio** [comment]
Multi-economy is being removed in https://github.com/DaPigGuy/PiggyShopUI/pull/40 (MultiEconomy no longer maintained)
