### ISSUE TITLE
The game closes when I open a category

### ISSUE THREAD

**Issue by UnEnanoMas** [DaPigGuy/PiggyShopUI#34]
Please make sure your issue complies with these guidelines:
- * [*] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [*] Issue must have not been reported previously
- * [*] Make sure you are on the latest version of PMMP & PiggyShopUI
- * [*] Have a detailed title.

It does not give any crash on the console, the game only closes when you try to open a category

It only happened to me with the category of Armor, the others work well, when I add all the leather armor equipment, I try to open it and automatically the game closes.

https://drive.google.com/file/d/1Z-584rP-HTjJ9ANXXNNVl7BIz8beFLzT/view?usp=sharing (Video)

**Comment by Aericio** [comment]
Is this still an issue? Try re-creating Armor category if you haven't already. 

Also, no permissions to see the video.
