### ISSUE TITLE
A permission doesn´t exists

### ISSUE THREAD

**Issue by Mencoreh** [DaPigGuy/PiggyShopUI#35]
### Issue Description

- Expected result: Being able to put a private category that only certain people can access
- Actual result: No one (except op) can access because the permission does not exist

#### Steps to Reproduce the Issue
1. Create a category with any name (e.g food) and put it private
2. Give a player the permission piggyshopui.category.food
3. Try to access to that category with the user that "has" the permission
4. Type /fperms PiggyShopUI
5. Get realised that PiggyShopUI doesn´t have a permission called "piggyshopui.category." as seen on poggit page
### OS and Versions

* PocketMine-MP: 3.21.0
* PiggyShopUI: 2.1.1
* PHP: wtf
* Server OS: Pocketmine

### The permission  "piggyshopui.category." doesn´t exists, as seen on poggit page
![image](https://user-images.githubusercontent.com/84292106/123344674-f8342e00-d519-11eb-89e2-19a46f2ab289.png)

![imagen_2021-06-24_182312](https://user-images.githubusercontent.com/84292106/123344332-3e3cc200-d519-11eb-96a9-e39a6bd90097.png)

**Comment by Aericio** [comment]
See https://github.com/DaPigGuy/PiggyShopUI/blob/master/src/DaPigGuy/PiggyShopUI/shops/ShopCategory.php#L41-L42

**Comment by Aericio** [comment]
Might be a configuration error, since there were no API changes with permission registering and it was confirmed to work. I don't think anything is wrong here.

If we can get another person to confirm that there are issues, then I'll re-open the issue and look into it whenever I have time.
