### ISSUE TITLE
Error category,

### ISSUE THREAD

**Issue by llronaldoll** [DaPigGuy/PiggyShopUI#4]
**When adding the fifth item of the category, it does not work, only the first 4! can you help me ?**

`buy-main-menu-title: "PiggyShop Buy UI"
buy-category-menu-title: "{CATEGORY}"
buy-item-menu-title: "Buy {ITEM}"
buy-item-confirm-menu-title: "Confirm Transaction"
buy-categories:
  - name: "Blocos"
    image: "http://localhost/Blackhatsite/minecraft/img/cobblestone.png"
    image-type: 1
    items:
      - menu-name: "Pedra"
        id: 1
        damage: 0
        price: 10
        image: "http://localhost/Blackhatsite/minecraft/img/stone.png"
        image-type: 1
      - menu-name: "Pedregulho"
        id: 4
        damage: 0
        price: 5
        image: "http://localhost/Blackhatsite/minecraft/img/cobblestone.png"
        image-type: 1
      - menu-name: "Terra"
        id: 3
        damage: 0
        price: 3
        image: "http://localhost/Blackhatsite/minecraft/img/dirt.png"
        image-type: 1
      - menu-name: "Andesito Polido"
        id: 1
        damage: 6
        price: 1
        image: "http://localhost/Blackhatsite/minecraft/img/andesite.png"
        image-type: 1
      - menu-name: "Lampada de Redstone"
        id: 123
        damage: 0
        price: 1
        image: "http://localhost/Blackhatsite/minecraft/img/redstone_lamp.png"
        image-type: 1
      - menu-name: "Lampada de Redstone acesa"
        id: 89
        damage: 0
        price: 1
        image: "http://localhost/Blackhatsite/minecraft/img/redstone_lamp_on.png"
        image-type: 1
  - name: "Armas"
    image: "http://localhost/Blackhatsite/minecraft/img/diamond_sword.png"
    image-type: 1
    items:
      - menu-name: "Espada de Madeira"
        id: 268
        damage: 0
        price: 200
        image: "http://localhost/Blackhatsite/minecraft/img/wooden_sword.png"
        image-type: 0
      - menu-name: "Espada de Pedra"
        id: 123
        damage: 0
        price: 10
        image: "http://localhost/Blackhatsite/minecraft/img/stone_sword.png"
        image-type: 1
      - menu-name: "Espada de Ferro"
        id: 3
        damage: 0
        price: 1
        image: "http://localhost/Blackhatsite/minecraft/img/iron_sword.png"
        image-type: 1
  - name: "Ferramentas"
    image: "http://localhost/Blackhatsite/minecraft/img/diamond_pickaxe.png"
    image-type: 1
    items:
      - menu-name: "Picareta de Diamante"
        id: 278
        damage: 0
        price: 200
        image: "http://localhost/Blackhatsite/minecraft/img/diamond_pickaxe.png"
        image-type: 0
      - menu-name: "Picareta de Ouro"
        id: 285
        damage: 0
        price: 200
        image: "http://localhost/Blackhatsite/minecraft/img/golden_pickaxe.png"
        image-type: 1
      - menu-name: "Picareta de Ferro"
        id: 257
        damage: 0
        price: 10
        image: "http://localhost/Blackhatsite/minecraft/img/iron_pickaxe.png"
        image-type: 0
      - menu-name: "Picareta de Madeira"
        id: 270
        damage: 0
        price: 100
        image: "http://localhost/Blackhatsite/minecraft/img/wooden_pickaxe.png"
        image-type: 1
      - menu-name: "Picareta de Pedra"
        id: 274
        damage: 0
        price: 10
        image: "http://localhost/Blackhatsite/minecraft/img/stone_pickaxe.png"
        image-type: 1
  - name: "Comida"
    image: "https://media.forgecdn.net/avatars/64/819/636156733139658109.png"
    image-type: 1
    items:
      - menu-name: "Steak"
        id: 364
        damage: 0
        price: 10
        image: "textures/items/beef_cooked"
        image-type: 0
      - menu-name: "Cooked Chicken"
        id: 366
        damage: 0
        price: 10
        image: "textures/items/chicken_cooked"
        image-type: 0
      - menu-name: "Bread"
        id: 297
        damage: 0
        price: 5
        image: "textures/items/bread"
        image-type: 0
      - menu-name: "Maça"
        id: 260
        damage: 0
        price: 5
        image: "http://localhost/Blackhatsite/minecraft/img/apple.png"
        image-type: 1
sell-main-menu-title: "PiggyShop Sell UI"
sell-category-menu-title: "{CATEGORY}"
sell-item-menu-title: "Sell {ITEM}"
sell-item-confirm-menu-title: "Confirm Transaction"
sell-categories:
  - name: "Blocks"
    image: "http://www.blocksandgold.com//media/catalog/product/cache/3/image/200x/6cffa5908a86143a54dc6ad9b8a7c38e/c/o/cobblestone_6.png"
    image-type: 1
    items:
      - menu-name: "Stone"
        id: 1
        damage: 0
        price: 2.5
        image: "textures/blocks/stone"
        image-type: 0
      - menu-name: "Grass"
        id: 2
        damage: 0
        price: 5
        image: "textures/blocks/grass_side_carried"
        image-type: 0
      - menu-name: "Dirt"
        id: 3
        damage: 0
        price: 0.5
        image: "textures/blocks/dirt"
        image-type: 0
  - name: "Food"
    image: "https://media.forgecdn.net/avatars/64/819/636156733139658109.png"
    image-type: 1
    items:
      - menu-name: "Steak"
        id: 364
        damage: 0
        price: 5
        image: "textures/items/beef_cooked"
        image-type: 0
      - menu-name: "Cooked Chicken"
        id: 366
        damage: 0
        price: 5
        image: "textures/items/chicken_cooked"
        image-type: 0
      - menu-name: "Bread"
        id: 297
        damage: 0
        price: 2.5
        image: "textures/items/bread"
        image-type: 0
messages:
  buy-item-information: "{ITEM} cost ${PRICE} each."
  sell-item-information: "{ITEM} sell for ${PRICE} each."
  buy-item-confirmation: "Are you sure you would like to buy {COUNT}x {ITEM} for ${PRICE}."
  not-enough-money: "You do not have the required money to buy {COUNT}x {ITEM}. You are missing ${MISSING}."
  successfully-bought-item: "You have successfully bought {COUNT}x {ITEM} for ${PRICE}."
  sell-item-confirmation: "Are you sure you would like to sell {COUNT}x {ITEM} for ${PRICE}."
  missing-items: "You do not have {COUNT}x {ITEM}."
  successfully-sold-item: "You have successfully sold {COUNT}x {ITEM} for ${PRICE}."
  back-button: "Voltar"`

**Comment by Aericio** [comment]
What do you mean by "does not work"? Be more specific please.

**Comment by llronaldoll** [comment]
**happens in all categories I add more than 4 items always 5 does not work**

`buy-main-menu-title: "PiggyShop Buy UI"
buy-category-menu-title: "{CATEGORY}"
buy-item-menu-title: "Buy {ITEM}"
buy-item-confirm-menu-title: "Confirm Transaction"
buy-categories:
  - name: "Blocos"
    image: "http://localhost/Blackhatsite/minecraft/img/cobblestone.png"
    image-type: 1
    items:
      - menu-name: "Pedra"
        id: 1
        damage: 0
        price: 10
        image: "http://localhost/Blackhatsite/minecraft/img/stone.png"
        image-type: 1
      - menu-name: "Pedregulho"
        id: 4
        damage: 0
        price: 5
        image: "http://localhost/Blackhatsite/minecraft/img/cobblestone.png"
        image-type: 1
      - menu-name: "Terra"
        id: 3
        damage: 0
        price: 3
        image: "http://localhost/Blackhatsite/minecraft/img/dirt.png"
        image-type: 1
      - menu-name: "Andesito Polido"
        id: 1
        damage: 6
        price: 1
        image: "http://localhost/Blackhatsite/minecraft/img/andesite.png"
        image-type: 1
      - menu-name: "Lampada de Redstone"
        id: 123
        damage: 0
        price: 1
        image: "http://localhost/Blackhatsite/minecraft/img/redstone_lamp.png"
        image-type: 1
      - menu-name: "Lampada de Redstone acesa"
        id: 89
        damage: 0
        price: 1
        image: "http://localhost/Blackhatsite/minecraft/img/redstone_lamp_on.png"
        image-type: 1
  - name: "Armas"
    image: "http://localhost/Blackhatsite/minecraft/img/diamond_sword.png"
    image-type: 1
    items:
      - menu-name: "Espada de Madeira"
        id: 268
        damage: 0
        price: 200
        image: "http://localhost/Blackhatsite/minecraft/img/wooden_sword.png"
        image-type: 0
      - menu-name: "Espada de Pedra"
        id: 123
        damage: 0
        price: 10
        image: "http://localhost/Blackhatsite/minecraft/img/stone_sword.png"
        image-type: 1
      - menu-name: "Espada de Ferro"
        id: 3
        damage: 0
        price: 1
        image: "http://localhost/Blackhatsite/minecraft/img/iron_sword.png"
        image-type: 1
  - name: "Ferramentas"
    image: "http://localhost/Blackhatsite/minecraft/img/diamond_pickaxe.png"
    image-type: 1
    items:
      - menu-name: "Picareta de Diamante"
        id: 278
        damage: 0
        price: 200
        image: "http://localhost/Blackhatsite/minecraft/img/diamond_pickaxe.png"
        image-type: 0
      - menu-name: "Picareta de Ouro"
        id: 285
        damage: 0
        price: 200
        image: "http://localhost/Blackhatsite/minecraft/img/golden_pickaxe.png"
        image-type: 1
      - menu-name: "Picareta de Ferro"
        id: 257
        damage: 0
        price: 10
        image: "http://localhost/Blackhatsite/minecraft/img/iron_pickaxe.png"
        image-type: 0
      - menu-name: "Picareta de Madeira"
        id: 270
        damage: 0
        price: 100
        image: "http://localhost/Blackhatsite/minecraft/img/wooden_pickaxe.png"
        image-type: 1
      - menu-name: "Picareta de Pedra"
        id: 274
        damage: 0
        price: 10
        image: "http://localhost/Blackhatsite/minecraft/img/stone_pickaxe.png"
        image-type: 1
  - name: "Comida"
    image: "https://media.forgecdn.net/avatars/64/819/636156733139658109.png"
    image-type: 1
    items:
      - menu-name: "Steak"
        id: 364
        damage: 0
        price: 10
        image: "textures/items/beef_cooked"
        image-type: 0
      - menu-name: "Cooked Chicken"
        id: 366
        damage: 0
        price: 10
        image: "textures/items/chicken_cooked"
        image-type: 0
      - menu-name: "Bread"
        id: 297
        damage: 0
        price: 5
        image: "textures/items/bread"
        image-type: 0
      - menu-name: "Maça"
        id: 260
        damage: 0
        price: 5
        image: "http://localhost/Blackhatsite/minecraft/img/apple.png"
        image-type: 1
      - menu-name: "Melancia"
        id: 360
        damage: 0
        price: 5
        image: "http://localhost/Blackhatsite/minecraft/img/melon.png"
        image-type: 1
sell-main-menu-title: "PiggyShop Sell UI"
sell-category-menu-title: "{CATEGORY}"
sell-item-menu-title: "Sell {ITEM}"
sell-item-confirm-menu-title: "Confirm Transaction"
sell-categories:
  - name: "Blocks"
    image: "http://www.blocksandgold.com//media/catalog/product/cache/3/image/200x/6cffa5908a86143a54dc6ad9b8a7c38e/c/o/cobblestone_6.png"
    image-type: 1
    items:
      - menu-name: "Stone"
        id: 1
        damage: 0
        price: 2.5
        image: "textures/blocks/stone"
        image-type: 0
      - menu-name: "Grass"
        id: 2
        damage: 0
        price: 5
        image: "textures/blocks/grass_side_carried"
        image-type: 0
      - menu-name: "Dirt"
        id: 3
        damage: 0
        price: 0.5
        image: "textures/blocks/dirt"
        image-type: 0
  - name: "Food"
    image: "https://media.forgecdn.net/avatars/64/819/636156733139658109.png"
    image-type: 1
    items:
      - menu-name: "Steak"
        id: 364
        damage: 0
        price: 5
        image: "textures/items/beef_cooked"
        image-type: 0
      - menu-name: "Cooked Chicken"
        id: 366
        damage: 0
        price: 5
        image: "textures/items/chicken_cooked"
        image-type: 0
      - menu-name: "Bread"
        id: 297
        damage: 0
        price: 2.5
        image: "textures/items/bread"
        image-type: 0
messages:
  buy-item-information: "{ITEM} cost ${PRICE} each."
  sell-item-information: "{ITEM} sell for ${PRICE} each."
  buy-item-confirmation: "Are you sure you would like to buy {COUNT}x {ITEM} for ${PRICE}."
  not-enough-money: "You do not have the required money to buy {COUNT}x {ITEM}. You are missing ${MISSING}."
  successfully-bought-item: "You have successfully bought {COUNT}x {ITEM} for ${PRICE}."
  sell-item-confirmation: "Are you sure you would like to sell {COUNT}x {ITEM} for ${PRICE}."
  missing-items: "You do not have {COUNT}x {ITEM}."
  successfully-sold-item: "You have successfully sold {COUNT}x {ITEM} for ${PRICE}."
  back-button: "Voltar"`
