### ISSUE TITLE
how am i suppose too know how too format the shop.yml when there is no example

### ISSUE THREAD

**Issue by Johnathen8** [DaPigGuy/PiggyShopUI#48]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyShopUI
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### OS and Versions

* PocketMine-MP:
* PiggyShopUI:
* PHP:
* Server OS:

### Extra Information

**Comment by Aericio** [comment]
You don't edit the config. You're supposed to edit it with the command.

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyShopUI#installation--setup
