### ISSUE TITLE
Crashes when server starts

### ISSUE THREAD

**Issue by LeoWasCoding** [DaPigGuy/PiggyShopUI#49]
Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of DaPigGuy\PiggyShopUI\libs\jojoe77777\FormAPI\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/container/plugins/PiggyShopUI_dev-74.phar/src/DaPigGuy/PiggyShopUI/libs/jojoe77777/FormAPI/Form.php:53
Stack trace:
#0 phar:///home/container/plugins/PiggyShopUI_dev-74.phar/src/DaPigGuy/PiggyShopUI/libs/jojoe77777/FormAPI/Form.php(10): pocketmine\errorhandler\ErrorToExceptionHandler::handle(8192, 'Return type of ...', 'phar:///home/co...', 53)
#1 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar:///home/co...')
#2 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('DaPigGuy\\PiggyS...')
#3 [internal function]: BaseClassLoader->{closure}('DaPigGuy\\PiggyS...')
#4 phar:///home/container/plugins/PiggyShopUI_dev-74.phar/src/DaPigGuy/PiggyShopUI/PiggyShopUI.php(41): class_exists('DaPigGuy\\PiggyS...')
#5 phar:///home/container/PocketMine-MP.phar/src/plugin/PluginBase.php(118): DaPigGuy\PiggyShopUI\PiggyShopUI->onEnable()
#6 phar:///home/container/PocketMine-MP.phar/src/plugin/PluginManager.php(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#7 phar:///home/container/PocketMine-MP.phar/src/Server.php(1402): pocketmine\plugin\PluginManager->enablePlugin(Object(DaPigGuy\PiggyShopUI\PiggyShopUI))
#8 phar:///home/container/PocketMine-MP.phar/src/Server.php(1037): pocketmine\Server->enablePlugins(Object(pocketmine\plugin\PluginEnableOrder))
#9 phar:///home/container/PocketMine-MP.phar/src/PocketMine.php(336): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), '/home/container...', '/home/container...')
#10 phar:///home/container/PocketMine-MP.phar/src/PocketMine.php(359): pocketmine\server()
#11 /home/container/PocketMine-MP.phar(11): require('phar:///home/co...')
#12 {main} in phar:///home/container/plugins/PiggyShopUI_dev-74.phar/src/DaPigGuy/PiggyShopUI/libs/jojoe77777/FormAPI/Form.php on line 10
[15:44:45.216] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[15:44:45.223] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Wed_May_24-15.44.45-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[Tue_May_23-16.19.28-UTC_2023.log](https://github.com/DaPigGuy/PiggyShopUI/files/11556577/Tue_May_23-16.19.28-UTC_2023.log)

**Comment by SillierShark195** [comment]
> Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of DaPigGuy\PiggyShopUI\libs\jojoe77777\FormAPI\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/container/plugins/PiggyShopUI_dev-74.phar/src/DaPigGuy/PiggyShopUI/libs/jojoe77777/FormAPI/Form.php:53 Stack trace: #0 phar:///home/container/plugins/PiggyShopUI_dev-74.phar/src/DaPigGuy/PiggyShopUI/libs/jojoe77777/FormAPI/Form.php(10): pocketmine\errorhandler\ErrorToExceptionHandler::handle(8192, 'Return type of ...', 'phar:///home/co...', 53) #1 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar:///home/co...') #2 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('DaPigGuy\PiggyS...') #3 [internal function]: BaseClassLoader->{closure}('DaPigGuy\PiggyS...') #4 phar:///home/container/plugins/PiggyShopUI_dev-74.phar/src/DaPigGuy/PiggyShopUI/PiggyShopUI.php(41): class_exists('DaPigGuy\PiggyS...') #5 phar:///home/container/PocketMine-MP.phar/src/plugin/PluginBase.php(118): DaPigGuy\PiggyShopUI\PiggyShopUI->onEnable() #6 phar:///home/container/PocketMine-MP.phar/src/plugin/PluginManager.php(454): pocketmine\plugin\PluginBase->onEnableStateChange(true) #7 phar:///home/container/PocketMine-MP.phar/src/Server.php(1402): pocketmine\plugin\PluginManager->enablePlugin(Object(DaPigGuy\PiggyShopUI\PiggyShopUI)) #8 phar:///home/container/PocketMine-MP.phar/src/Server.php(1037): pocketmine\Server->enablePlugins(Object(pocketmine\plugin\PluginEnableOrder)) #9 phar:///home/container/PocketMine-MP.phar/src/PocketMine.php(336): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), '/home/container...', '/home/container...') #10 phar:///home/container/PocketMine-MP.phar/src/PocketMine.php(359): pocketmine\server() #11 /home/container/PocketMine-MP.phar(11): require('phar:///home/co...') #12 {main} in phar:///home/container/plugins/PiggyShopUI_dev-74.phar/src/DaPigGuy/PiggyShopUI/libs/jojoe77777/FormAPI/Form.php on line 10 [15:44:45.216] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump [15:44:45.223] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Wed_May_24-15.44.45-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can. [Tue_May_23-16.19.28-UTC_2023.log](https://github.com/DaPigGuy/PiggyShopUI/files/11556577/Tue_May_23-16.19.28-UTC_2023.log)

Fix by ur self is easy

**Comment by LeoWasCoding** [comment]
Im asking for help because idk. Mind telling me how?

**Comment by SillierShark195** [comment]
> Im asking for help because idk. Mind telling me how?

Cool name tho, because im good guy discord me

My discord id 520937655119118336

**Comment by LeoWasCoding** [comment]
> > Im asking for help because idk. Mind telling me how?
> 
> Cool name tho, because im good guy discord me
> 
> My discord id 520937655119118336

Added

**Comment by Aericio** [comment]
please check if the latest build works
https://poggit.pmmp.io/ci/DaPigGuy/PiggyShopUI/~/dev:84

**Comment by LeoWasCoding** [comment]
> please check if the latest build works https://poggit.pmmp.io/ci/DaPigGuy/PiggyShopUI/~/dev:84

Tried all of them to the oldest and to the newest. No use.

**Comment by LeoWasCoding** [comment]
> did you actually download the latest one ![image](https://user-images.githubusercontent.com/16523741/240878684-fc72dc63-e48e-4e86-8264-08ebe88dca81.png)

New one came out huh imma download it

**Comment by VortexPMMP** [comment]
Just update the FormAPI DaPigGuy/FormAPI-4.0.0/Form.php 
Line 53 

Add : mixed next to jsonSerialize()

**Comment by VortexPMMP** [comment]
It would be : array hehe

**Comment by Aericio** [comment]
Resolved in v3.0.3
