### ISSUE TITLE
Use Signs to open ShopUI

### ISSUE THREAD

**Issue by llronaldoll** [DaPigGuy/PiggyShopUI#5]
make it possible to execute the buy and sell command through the console, to be used with the CommandShop plugin
or make possible the use of sign

**Comment by Aericio** [comment]
Console cannot buy/sell items.

ShopUI, as the name suggests, is a shop with an user interface. It may not be done.

**Comment by llronaldoll** [comment]
my server does not allow players to execute commands directly, I wish there was the possibility of clicking a card open the interface of shopui

**Comment by Aericio** [comment]
Ah, I see.

**Comment by xDanub** [comment]
Download GrabBag, and CommandShop. When player clicks the sign 
/as {player} shop

I know this is 9 mo old, but I thought I would solve this.

**Comment by Aericio** [comment]
That works too.

**Comment by Aericio** [comment]
Not going to do this, just use a plugin to open shop.
