### ISSUE TITLE
Multiple shops for different ranks

### ISSUE THREAD

**Issue by EduGH7** [DaPigGuy/PiggyShopUI#8]
Is already the option to make independent shops? Fue example with the command "/shop" I open one kind of shop, AMD with the command "/shop vip" I open another shop, like in the plugin CustomShopUI but this plugin will have the custom enchants!

**Comment by Aericio** [comment]
We're pretty inactive now regarding the maintaining of public plugins, so don't have any hopes.

**Comment by DaPigGuy** [comment]
Available in the 2.0.0 branch
