### ISSUE TITLE
You can support commands?

### ISSUE THREAD

**Issue by junxiesky** [DaPigGuy/PiggyShopUI#9]
Can support command shop

**Comment by Aericio** [comment]
It's meant just for forms.

**Comment by junxiesky** [comment]
> 它仅用于表格。

I mean, the store sells command

**Comment by Aericio** [comment]
我不明白，你说什么？

**Comment by junxiesky** [comment]
> 我不明白，你说什么？

The store sells command, for example: I bought / give Steve 264 1 for 30 game coins

**Comment by Aericio** [comment]
不能。
